import type { Metadata } from 'next'
import Navbar from './_components/navbar'
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import {TRPCReactProvider} from '~/trpc/react'
import '~/styles/globals.css'
import { ToastProvider } from './_components/ToastProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>

      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <TRPCReactProvider>
            
          <ToastProvider>
          <Navbar />
          {children}
          </ToastProvider>
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}